kind: Service
apiVersion: v1
  name: testing
  namespace: rolebinding
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: testing
  type: ClusterIP
